import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBarComponent from "./Components/NavBarComponent/NavBarComponent";
import logo from "./../public/img/logo.png";
import FooterComponent from "./Components/FooterComponent/FooterComponent";
import { liContent, webLang } from "./Data/Data";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBarComponent img={logo} webLang={webLang} liContent={liContent} />
        {children}
        <FooterComponent logo={logo} />
      </body>
    </html>
  );
}
